flags:
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- MonadRandom-0.4.2.3
- QuickCheck-2.9.1
- StateVar-1.1.0.4
- ansi-terminal-0.6.2.3
- async-2.1.0
- base-orphans-0.5.4
- bifunctors-5.4.1
- boxes-0.1.4
- cmdargs-0.10.14
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- either-4.4.1.1
- exceptions-0.8.3
- free-4.12.4
- hashable-1.2.4.0
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- parsec-3.1.11
- prelude-extras-0.4.0.3
- pretty-tree-0.1.0.0
- primitive-0.6.1.0
- profunctors-5.2
- quickcheck-io-0.1.3
- random-1.1
- repline-0.1.5.0
- semigroupoids-5.1
- semigroups-0.18.2
- setenv-0.1.1.3
- split-0.2.3.1
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- void-0.7.1
resolver: ghc-7.10.3
